[package]
name = "triword"
version = "0.1.0"
edition = "2021"
authors = ["cdrani"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[test]]
name ="test_suite"
path = "src/test.rs"
